# Generated by Django 5.2.3 on 2026-05-05 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_module_livesession_module_syllabus_module_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='vimeo_video_id',
            field=models.CharField(blank=True, help_text='Vimeo video ID for embedded playback', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
