# Generated by Django 5.2.3 on 2026-05-05 08:15

import content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_video_vimeo_video_id_alter_video_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/', validators=[content.models.validate_video_file_size, content.models.validate_video_file_format]),
        ),
    ]
