# Generated by Django 5.2.3 on 2026-05-05 08:15

import assignment.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0008_merge_20251104_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='file',
            field=models.FileField(upload_to='assignments/', validators=[assignment.models.validate_assignment_file_size, assignment.models.validate_assignment_file_format]),
        ),
    ]
